import http from "node:http";
import { readFileSync, existsSync } from "node:fs";
import { extname, join, resolve, normalize, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const APP_DIR = join(__dirname, "app");
const PORT = Number(process.env.PORT || 10000);
const META_API_BASE = String(process.env.META_API_BASE || "https://inverterzone-dashboard.onrender.com").replace(/\/$/, "");
const MATRIX_API_BASE = String(process.env.MATRIX_API_BASE || "https://fronus-matrix-dashboard.onrender.com").replace(/\/$/, "");
const RATE = Number(process.env.ELECTRICITY_RATE_PKR || 60);

const MIME = { ".html":"text/html; charset=utf-8", ".css":"text/css; charset=utf-8", ".js":"text/javascript; charset=utf-8", ".json":"application/json; charset=utf-8", ".svg":"image/svg+xml" };

function json(res, code, body) { const text = JSON.stringify(body); res.writeHead(code, { "Content-Type":"application/json; charset=utf-8", "Cache-Control":"no-store" }); res.end(text); }
function num(v, f=0){ const n = typeof v === "number" ? v : Number.parseFloat(String(v ?? "").replaceAll(",","")); return Number.isFinite(n) ? n : f; }
function unwrap(payload){ let v=payload; for(let i=0;i<5;i++){ if(Array.isArray(v)&&v.length){v=v[0];continue;} if(!v||typeof v!=="object") break; const k=["dataDTO","data","result","reading","telemetry"].find(x=>v[x]&&typeof v[x]==="object"); if(!k) break; v=v[k]; } return v&&typeof v==="object"?v:{}; }
function first(s, keys, f=0){ for(const k of keys) if(Object.prototype.hasOwnProperty.call(s,k)) return num(s[k],f); return f; }
function dir(gridW){ return Math.abs(gridW)<30 ? "IDLE" : gridW >= 0 ? "IMPORTING" : "EXPORTING"; }

async function getJson(url, timeoutMs=15000){ const ac = new AbortController(); const t=setTimeout(()=>ac.abort(), timeoutMs); try{ const r=await fetch(url,{signal:ac.signal,headers:{"User-Agent":"Raja-Fraz-Master/1.0"}}); const text=await r.text(); let data; try{data=JSON.parse(text);}catch{data={raw:text};} if(!r.ok) throw new Error(data?.error||data?.msg||`HTTP ${r.status}`); return data; } finally{ clearTimeout(t); } }

function normalizeMeta(payload){ const s=unwrap(payload); const solar=first(s,["solarWatts","solarW","pvWatts","PV_Total_Power"]); const load=first(s,["loadWatts","acOutW","loadPower","AC_out_Watt"]); const grid=first(s,["gridWatts","gridW","gridPower","Grid_Watt"]); const batteryPct=first(s,["batteryPercentage","battPercent","batterySoc"],NaN); return { key:"meta", name:"Fronus Meta PV9000", online:true, solarW:solar, pv1W:first(s,["pv1Watts","solarW1","pv1_power"]), pv2W:first(s,["pv2Watts","solarW2","pv2_power"]), loadW:load, gridW:grid, gridV:first(s,["gridVoltage","gridV","AC_in_Voltage"]), gridHz:first(s,["gridHz","gridFrequency"]), batteryPct:Number.isFinite(batteryPct)?batteryPct:null, batteryW:first(s,["batteryPowerWatts","batteryW"],0), smartLoadW:0, acOutW:first(s,["inverterOutputWatts","acOutW"],load), temp:first(s,["heatSinkTemperature","heatSinkDegC","inverterTemperature"],0), fan:first(s,["fanSpeed","fan"],0), signal:first(s,["signal","wifiSignal"],0), todaySolar:first(s,["todaySolar","solarToday"],0), todayLoad:first(s,["todayLoad","loadToday"],0), todayImport:first(s,["todayGrid","todayImport","gridImportToday"],0), todayExport:first(s,["todayNetGrid","todayExport","gridExportToday"],0), health:"Excellent", updatedAt:num(s.receivedAt||s.timestamp||Date.now()) }; }
function normalizeMatrix(payload){ const s=unwrap(payload); const grid=first(s,["gridWatts","gridW"]); return { key:"matrix", name:"Fronus Matrix 6K", online:true, solarW:first(s,["solarWatts","solarW"]), pv1W:first(s,["pv1Watts","solarW1"]), pv2W:first(s,["pv2Watts","solarW2"]), loadW:first(s,["loadWatts","acOutW"]), gridW:grid, gridV:first(s,["gridVoltage","gridV"]), gridHz:first(s,["gridHz"],0), batteryPct:first(s,["batteryPercentage","battPercent"],null), batteryW:first(s,["batteryPowerWatts","batteryW"],0), batteryMode:String(s.batteryMode||"--"), smartLoadW:first(s,["smartLoadWatts"],0), acOutW:first(s,["inverterOutputWatts","acOutW"],0), temp:first(s,["heatSinkTemperature","radiatorTemperature","transformerTemperature"],0), transformer:first(s,["transformerTemperature"],0), radiator:first(s,["radiatorTemperature"],0), todaySolar:first(s,["todaySolar"],0), todayLoad:first(s,["todayLoad"],0), todayImport:first(s,["todayGrid"],0), todayExport:first(s,["todayNetGrid"],0), todaySmartLoad:first(s,["todaySmartLoad"],0), health:"Excellent", updatedAt:num(s.receivedAt||Date.now()) }; }
function combine(a,b){ const systems=[a,b].filter(Boolean); const sum=(k)=>systems.reduce((t,x)=>t+num(x[k]),0); const grid=sum("gridW"); return { key:"combined", name:"Combined Site", online:systems.some(x=>x.online), solarW:sum("solarW"), pv1W:sum("pv1W"), pv2W:sum("pv2W"), loadW:sum("loadW"), gridW:grid, smartLoadW:sum("smartLoadW"), batteryW:sum("batteryW"), todaySolar:sum("todaySolar"), todayLoad:sum("todayLoad"), todayImport:sum("todayImport"), todayExport:sum("todayExport"), netSiteW:sum("solarW") + Math.max(0, -grid) - sum("loadW"), gridDirection:dir(grid), health:"Excellent" }; }
async function fetchLive(){ const out={}; const errors={}; const [meta,matrix]=await Promise.allSettled([getJson(`${META_API_BASE}/api/live?fresh=1`).then(normalizeMeta), getJson(`${MATRIX_API_BASE}/api/matrix`).then(normalizeMatrix)]); if(meta.status==="fulfilled") out.meta=meta.value; else errors.meta=meta.reason.message; if(matrix.status==="fulfilled") out.matrix=matrix.value; else errors.matrix=matrix.reason.message; out.combined=combine(out.meta,out.matrix); return { ok:Object.keys(out).length>1, systems:out, errors, updatedAt:Date.now(), refreshSeconds:10, solarmanFrameSeconds:60, rate:RATE }; }
async function fetchHistory(hours=24){ const [meta,matrix]=await Promise.allSettled([getJson(`${META_API_BASE}/api/history?hours=${hours}`), getJson(`${MATRIX_API_BASE}/api/history?hours=${hours}`)]); const norm=(payload,kind)=> (unwrap(payload).data||payload.data||[]).map(p=>({ timestamp:num(p.timestamp||p.receivedAt||Date.now()), solarW:num(p.solarW), loadW:num(p.loadW), gridW:num(p.gridW), pv1W:num(p.pv1W), pv2W:num(p.pv2W), smartLoadW:num(p.smartLoadW) })); const mh = meta.status==="fulfilled" ? norm(meta.value,"meta") : []; const mxh = matrix.status==="fulfilled" ? norm(matrix.value,"matrix") : []; return { ok:true, meta:mh, matrix:mxh }; }
async function fetchWeather(){ try{ const w=await getJson(`${MATRIX_API_BASE}/api/weather`, 8000); return { ok:true, data:unwrap(w) }; } catch(e){ return { ok:false, error:e.message }; } }

function staticPath(urlPath){ const rel = urlPath === "/" ? "index.html" : decodeURIComponent(urlPath.split("?")[0]).replace(/^\/+/,""); const abs = resolve(APP_DIR, normalize(rel)); const root = resolve(APP_DIR)+sep; return abs.startsWith(root) ? abs : null; }

const server=http.createServer(async (req,res)=>{ try{ const url=new URL(req.url, `http://${req.headers.host||"localhost"}`); if(url.pathname==="/api/master/live") return json(res,200,await fetchLive()); if(url.pathname==="/api/master/history") return json(res,200,await fetchHistory(Math.max(1, Math.min(720, num(url.searchParams.get("hours"),24))))); if(url.pathname==="/api/master/weather") return json(res,200,await fetchWeather()); if(url.pathname==="/api/health") return json(res,200,{success:true,service:"Raja Fraz Master Dashboard", meta:META_API_BASE, matrix:MATRIX_API_BASE}); const p=staticPath(url.pathname); if(!p||!existsSync(p)) { res.writeHead(404,{"Content-Type":"text/plain"}); return res.end("Not found"); } const b=readFileSync(p); res.writeHead(200,{"Content-Type":MIME[extname(p)]||"application/octet-stream"}); res.end(b); }catch(e){ json(res,500,{ok:false,error:e.message}); } });
server.listen(PORT,()=>console.log(`Raja Fraz Master Dashboard running on ${PORT}`));
