const $=id=>document.getElementById(id);const $$=s=>Array.from(document.querySelectorAll(s));const fmt=(w)=>{w=Number(w)||0;return Math.abs(w)>=1000?`${(Math.abs(w)/1000).toFixed(2)} kW`:`${Math.round(Math.abs(w))} W`};const kwh=x=>`${(Number(x)||0).toFixed(2)} kWh`;const pct=(v,max)=>Math.max(0,Math.min(100,(Math.abs(Number(v)||0)/max)*100));let live=null,history={meta:[],matrix:[]};
function set(id,t){const n=$(id);if(n)n.textContent=t}function gauge(id,p,color){const n=$(id);if(n){n.style.strokeDasharray=`${Math.max(0,Math.min(100,p)).toFixed(2)} 100`; if(color){n.classList.remove('red','green');n.classList.add(color)}}}
function clock(){const d=new Date();set('clock',d.toLocaleTimeString('en-GB',{hour12:false}));set('date',d.toLocaleDateString('en-PK',{weekday:'short',day:'2-digit',month:'short'}))}setInterval(clock,1000);clock();
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active');drawAll()});
async function load(){try{const r=await fetch('/api/master/live',{cache:'no-store'});live=await r.json();render();set('liveChip','● LIVE');$('liveChip').classList.add('live')}catch(e){set('liveChip','● ERROR')}try{const h=await fetch('/api/master/history?hours=24',{cache:'no-store'});history=await h.json();drawAll()}catch(e){}}
async function weather(){try{const r=await fetch('/api/master/weather');const w=await r.json();const d=w.data||{};if(d.temperature||d.temperature_2m)set('weather',`☁ ${Math.round(d.temperature||d.temperature_2m)}° Gujrat`)}catch(e){}}
function render(){if(!live)return;const s=live.systems||{},c=s.combined||{},m=s.meta||{},x=s.matrix||{};const gridMode=c.gridW>=0?'IMPORTING':'EXPORTING';set('cSolar',fmt(c.solarW));set('cLoad',fmt(c.loadW));set('cGrid',fmt(c.gridW));set('cGridMode',gridMode);set('cBattery',x.batteryPct!=null?`${Math.round(x.batteryPct)}%`:'--');set('gLoadText',fmt(c.loadW));set('gSolarText',fmt(c.solarW));set('gGridText',fmt(c.gridW));set('gGridSub',gridMode);set('gSmartText',fmt(c.smartLoadW));gauge('gLoad',pct(c.loadW,12000));gauge('gSolar',pct(c.solarW,11140));gauge('gGrid',pct(c.gridW,12000),c.gridW>=0?'red':'green');gauge('gSmart',pct(c.smartLoadW,6000));set('metaMini',fmt(m.solarW));set('matrixMini',fmt(x.solarW));set('smartMini',fmt(c.smartLoadW));set('metaStatus',m.online?'ONLINE':'OFFLINE');set('matrixStatus',x.online?'ONLINE':'OFFLINE');set('metaLine',`${fmt(m.solarW)} solar · ${fmt(m.loadW)} load · ${fmt(m.gridW)} grid`);set('matrixLine',`${fmt(x.solarW)} solar · ${fmt(x.loadW)} load · ${fmt(x.smartLoadW)} smart load`);set('todaySolar',kwh(c.todaySolar));set('todayLoad',kwh(c.todayLoad));set('todayImport',kwh(c.todayImport));set('todayExport',kwh(c.todayExport));set('totSolar',kwh(c.todaySolar));set('totLoad',kwh(c.todayLoad));set('totImport',kwh(c.todayImport));set('totExport',kwh(c.todayExport));set('solarValue',`PKR ${Math.round((c.todaySolar||0)*(live.rate||60)).toLocaleString()}`);details('metaDetails',m);details('matrixDetails',x);drawAll()}
function details(id,s){const rows=[['Solar',fmt(s.solarW)],['Load',fmt(s.loadW)],['Grid',fmt(s.gridW)],['Grid voltage',`${(s.gridV||0).toFixed(1)} V`],['PV1',fmt(s.pv1W)],['PV2',fmt(s.pv2W)],['Battery',s.batteryPct!=null?`${Math.round(s.batteryPct)}% · ${fmt(s.batteryW)}`:'Not active'],['Smart Load',fmt(s.smartLoadW)],['Temperature',`${Math.round(s.temp||0)} °C`],['Today solar',kwh(s.todaySolar)]];$(id).innerHTML=rows.map(r=>`<dt>${r[0]}</dt><dd>${r[1]}</dd>`).join('')}
function mergeHist(){const map=new Map();for(const [key,arr] of [['meta',history.meta||[]],['matrix',history.matrix||[]]])for(const p of arr){const t=Math.round((p.timestamp||Date.now())/60000)*60000;const o=map.get(t)||{timestamp:t,solarW:0,loadW:0,gridW:0,smartLoadW:0,pv1W:0,pv2W:0};o.solarW+=+p.solarW||0;o.loadW+=+p.loadW||0;o.gridW+=+p.gridW||0;o.smartLoadW+=+p.smartLoadW||0;o.pv1W+=+p.pv1W||0;o.pv2W+=+p.pv2W||0;map.set(t,o)}return [...map.values()].sort((a,b)=>a.timestamp-b.timestamp).slice(-140)}
function drawChart(id,series,opts={}){const c=$(id);if(!c)return;const r=c.getBoundingClientRect();const dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=r.height*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,r.width,r.height);const pad=34;ctx.strokeStyle='#d8e8f0';ctx.lineWidth=1;for(let i=0;i<5;i++){let y=pad+(r.height-pad*2)*i/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(r.width-pad,y);ctx.stroke()}const all=series.flatMap(s=>s.data.map(p=>p.v));const max=Math.max(1000,...all.map(Math.abs))*1.15;const plot=(s)=>{ctx.strokeStyle=s.color;ctx.lineWidth=2;ctx.beginPath();s.data.forEach((p,i)=>{const x=pad+(r.width-pad*2)*(i/Math.max(1,s.data.length-1));const y=r.height/2-(p.v/max)*(r.height/2-pad);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()};ctx.strokeStyle='#b8d0dc';ctx.beginPath();ctx.moveTo(pad,r.height/2);ctx.lineTo(r.width-pad,r.height/2);ctx.stroke();series.forEach(plot)}
function drawBars(){const c=$('barChart');if(!c||!live)return;const r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=r.height*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,r.width,r.height);const vals=[['Solar',live.systems.combined.todaySolar,'#f7b21b'],['Load',live.systems.combined.todayLoad,'#3b82f6'],['Import',live.systems.combined.todayImport,'#f04b5f'],['Export',live.systems.combined.todayExport,'#21ad70']];const max=Math.max(1,...vals.map(v=>v[1]));vals.forEach((v,i)=>{const x=80+i*(r.width-160)/4+40,w=58,h=(r.height-80)*(v[1]/max);ctx.fillStyle=v[2];ctx.fillRect(x,r.height-45-h,w,h);ctx.fillStyle='#062b46';ctx.font='800 15px Segoe UI';ctx.fillText(`${v[1].toFixed(2)} kWh`,x-8,r.height-55-h);ctx.fillStyle='#7390a3';ctx.fillText(v[0],x+6,r.height-18)})}
function drawAll(){const h=mergeHist();const ser=[{color:'#f7b21b',data:h.map(p=>({v:p.solarW}))},{color:'#3b82f6',data:h.map(p=>({v:p.loadW}))},{color:'#21ad70',data:h.map(p=>({v:-p.gridW}))},{color:'#fb8c24',data:h.map(p=>({v:p.smartLoadW}))}];drawChart('overviewChart',ser);drawChart('fullChart',ser);drawChart('gridChart',[{color:'#f04b5f',data:h.map(p=>({v:p.gridW}))}]);drawChart('pvChart',[{color:'#f7b21b',data:h.map(p=>({v:p.pv1W}))},{color:'#7c5cff',data:h.map(p=>({v:p.pv2W}))}]);drawBars()}
load();weather();setInterval(load,10000);setInterval(weather,600000);addEventListener('resize',drawAll);
